### ISSUE TITLE
Compiling paho.mqtt.c and paho.mqtt.cpp in same project

### ISSUE THREAD

**Issue by chrissyheb** [eclipse/paho.mqtt.cpp#225] opened 2019-10-28 12:22 UTC
Hello,
I am trying to build the C++ shared library as part of a bigger CMake project. To always have a up to date library I added the C and the C++ as git submodules to my project to compile them all together after changes. I don't want to change their CMakeLists.txt files to keep always the original version if possible.

So my simplified project structure looks like this:
main dir/
| -- CMakeLists.txt
| -- mainApp.cpp
| -- libs/
| -- | -- paho.mqtt.c/ (submodule with original CMakeLists.txt)
| -- | -- paho.mqtt.cpp/ (submodule with original CMakeLists.txt)

My top level CMakeLists.txt looks as follows:
```
cmake_minimum_required(VERSION 3.13)
project (pahoTest)

set(PAHO_WITH_SSL ON)
add_subdirectory(lib/paho.mqtt.c)

set(CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})
add_subdirectory(lib/paho.mqtt.cpp)

add_executable(app mainApp.cpp)
target_link_libraries(app paho-mqttpp3)
```

My problem is that the CMake cannot find the C libraries and exits with the error
```
lib/paho.mqtt.cpp/src/CMakeLists.txt:26 (find_package)
lib/paho.mqtt.cpp/cmake/FindPahoMqttC.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)
```
It's clear that the library is not there before the initial build. But how can I tell the C++ library to wait for the build of the C library?

Can someone please point me to the right CMake configuration to get it working? 

Thank you.
Chrissy

**Comment by fpagliughi** [comment] 2019-10-28 14:47
Apologies, I'm not much of a CMake expert, but maybe this will help:
[add_dependencies](https://cmake.org/cmake/help/v3.8/command/add_dependencies.html?highlight=i)

**Comment by fpagliughi** [comment] 2019-10-28 14:51
On a side note, however, I've really been considering having the C++ library automatically build (and maybe link in) the optimal version of the C lib by including it as a Git submodule to this project. It's a common source of errors and frustration to have to build two separate libraries and get them working together if you only care about using the C++ lib. 

I did something similar with the Paho Rust library, and it's eliminated a lot of confusion and problems. So I should probably do it here as well.

**Comment by chrissyheb** [comment] 2019-10-28 19:23
Hello,
I added the following lines to my CMakeLists.txt
```
add_dependencies(paho-mqttpp3 paho-mqttas)
add_dependencies(paho-mqttpp3 paho-mqttas)
add_dependencies(paho-mqttpp3 paho-mqttc)
add_dependencies(paho-mqttpp3 paho-mqttcs)
```
but it did not help.

> On a side note, however, I've really been considering having the C++ library automatically build (and maybe link in) the optimal version of the C lib by including it as a Git submodule to this project. It's a common source of errors and frustration to have to build two separate libraries and get them working together if you only care about using the C++ lib.
I did something similar with the Paho Rust library, and it's eliminated a lot of confusion and problems. So I should probably do it here as well.

That sounds good to me. Can I help somehow?

**Comment by saftkran** [comment] 2019-11-04 14:10
I'm having the exact same problem. I too think having the c++ library automatically build the optimal c lib would be very useful.

**Comment by fpagliughi** [comment] 2019-11-04 15:40
Agreed. I'll create a new issue for auto-building a Paho C Git submodule. The only thing that's slightly worrying is that the C lib uses an old-fashioned CMake 2.8 build style. I can imagine devolving into a tangent project to re-write the CMake for the C project as well.

**Comment by nedo99** [comment] 2019-12-06 12:50
I have a similar situation so just to check if this is the same issue. I've built the mqtt c library and installed it on custom location. 

When I want to build mqtt c++ I provide CMAKE_PREFIX_PATH with an absolute path to mqtt c custom install path, but I get:
`CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPahoMqttC.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
`

mqtt c git tag is v1.3.1
mqtt c++ git tag is v1.1

**Comment by nedo99** [comment] 2019-12-06 13:20
Found the alternative (or maybe it is the right way). I do `cmake` with

`cmake -DCMAKE_PREFIX_PATH=<absolute path to mqtt c install dir> -DPAHO_MQTT_C_LIBRARIES=<absolute  path to c libraries> -DPAHO_MQTT_C_INCLUDE_DIRS=<absolute  path to include headers> ..`
and configuration passes, but build then fails:
`
/usr/bin/ld: cannot find ../../paho.mqtt.c/build/install/lib: File format not recognized
`
but my library is not in `../../paho.mqtt.c/build/install/lib`, but in `../paho.mqtt.c/build/install/lib`. I provide absolute path so somewhere in cmake it gets resolved to wrong relative path.

**Comment by fpagliughi** [comment] 2019-12-07 15:50
Did you use CMake to build and install the Paho C library? Did it create the normal `include/` and `lib/` subdirectories? Are you cross-compiling?

**Comment by nedo99** [comment] 2019-12-08 22:23
Yes, as per description 
`$ cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_ENABLE_TESTING=OFF
$ sudo cmake --build build/ --target install
$ sudo ldconfig`. 

I just add the `CMAKE_INSTALL_PREFIX` for a custom location. Everything is there, lib, include and bin folder.

**Comment by fpagliughi** [comment] 2019-12-08 22:52
@nedo99  That's strange. I can't reproduce it on my machine.

This is actually my development setup... I use mostly Mint/Ubuntu versions of Linux, and I don't install Paho C onto the machine in a standard location, since I switch between different versions for testing. I keep the two library directories next to each other, and then build the C lib and install it into the build tree at: `paho.mqtt.c/build/_install/usr/local`.

Then I build the C++ lib using just `-DCMAKE_PREFIX_PATH=...` as described in the README.

Feel free to post your whole build output, for both libraries, including the commands, and maybe we can spot something. Or maybe then I can reproduce.

**Comment by nedo99** [comment] 2019-12-09 14:39
@fpagliughi here are the commands:
```
cd <workspace_folder>
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
git checkout v1.3.1
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=install -DPAHO_ENABLE_TESTING=OFF ..
make -j16
make install
```
After this I check, all install files are located under workspace_folder/paho.mqtt.c/build/install folder insluding lib, include folders.

Then I do:
```
cd ../../
git clone https://github.com/eclipse/paho.mqtt.cpp
cd paho.mqtt.cpp
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH= <workspace folder>/paho.mqtt.c/build/install ..
```

And I get the message:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPahoMqttC.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:26 (find_package)
```

I am using Ubuntu 18.04 with GCC 7.4.0.

**Comment by fpagliughi** [comment] 2019-12-09 19:24
For the C++ library, try:
```
cmake -DCMAKE_PREFIX_PATH= <workspace folder>/paho.mqtt.c/build/install/usr/local ..
```

**Comment by nedo99** [comment] 2019-12-10 12:42
Still the same. There is no usr/local since that I update the CMAKE_INSTALL_PREFIX when installing the C libary...

**Comment by magiino** [comment] 2020-02-15 21:45
I had the same problem, except I wanted build mqtt as **static** library. So maybe you can use my solution as example.

### Thanks to `rightback`, who provided me a solution !!!

#### You can see this solution 
 1. In my repository: `https://gitlab.com/diplomathesis/i40barman`
 2. Or in this post

Settings for build:
* `PAHO_BUILD_STATIC = TRUE`
* `PAHO_BUILD_WITH_SSL = FALSE`

# 1
Steps to run this project:
1. `>git clone https://gitlab.com/diplomathesis/i40barman.git`
2. `>git checkout 5600e271`    // checkout to commit where are these changes
3. `>git submodule update --init --recursive`
4. In project with name ***Product*** is in `main.cpp` ***paho.mqtt.cpp*** sample code from `https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/sync_publish.cpp`
5. Run the code. (I used ***mosquitto*** client for test if the code above works. `mosquitto_sub -h localhost -t "#"` -> mosquitto mqtt client subscribes to all topics)

# 2
**Project structure:**
project dir/
| -- **CMakeLists.txt**
| -- **fix_pahomqttcpp.cmake.in**
| -- **pahomqttc.cmake**
| -- **pahomqttcpp.cmake**
| -- src dir/
| -- | -- ...
| -- include dir/
| -- | -- ...
| -- lib dir/
| -- | -- **paho.mqtt.c/ (submodule with original CMakeLists.txt)**
| -- | -- **paho.mqtt.cpp/ (submodule with original CMakeLists.txt)**

## CMakeLists.txt
```
project(product)

# Find all source files with file extension .c/.cpp inside src folder
file(GLOB_RECURSE PROJECT_SRCS "src/*.c" "src/*.cpp")


# Settings for MQTT libraries
SET(PAHO_BUILD_STATIC TRUE)
SET(PAHO_BUILD_WITH_SSL FALSE)
include(pahomqttc.cmake)
include(pahomqttcpp.cmake)


# Add source files to project
add_executable(
    ${PROJECT_NAME}
    ${PROJECT_SRCS}
)

# Include project header files
target_include_directories(
    ${PROJECT_NAME}
    PUBLIC include
)

# Link MQTTlibraries to project
target_link_libraries(
    ${PROJECT_NAME}
    PRIVATE open62541-cpp-api
    PRIVATE paho-mqttpp3
    PRIVATE paho-mqttc3::MQTTAsync
)
```

## fix_pahomqttcpp.cmake.in
```
set(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} @PAHOMQTTC_INCLUDE_DIR@)
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} @PAHOMQTTC_LIBRARY_DIR@)
```

## pahomqttc.cmake
```
#
# Builds the paho.mqtt.c library
#
# This step is necessary to provide the libraries and
# headers for paho.mqtt.cpp project
#
include(ExternalProject)
set(PAHOMQTTC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lib/paho.mqtt.c)
set(PAHOMQTTC_TARGET_DIR ${CMAKE_CURRENT_BINARY_DIR}/paho.mqtt.c)

ExternalProject_Add(
    pahomqttc
    PREFIX ${PAHOMQTTC_TARGET_DIR}
    SOURCE_DIR ${PAHOMQTTC_DIR}
	 CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${PAHOMQTTC_TARGET_DIR}
	 CMAKE_ARGS -DPAHO_WITH_SSL=${PAHO_BUILD_WITH_SSL}
	 CMAKE_ARGS -DPAHO_BUILD_STATIC=${PAHO_BUILD_STATIC}
    BUILD_COMMAND make
	 INSTALL_COMMAND make install
)

# The paho.mqtt.cpp project needs to know where the paho.mqtt.c libraries
# and headers are installed, so we provide this information in an additional
# cmake file which is passed to the paho.mqtt.cpp project build
set(PAHOMQTTC_INCLUDE_DIR ${PAHOMQTTC_TARGET_DIR}/include)
set(PAHOMQTTC_LIBRARY_DIR ${PAHOMQTTC_TARGET_DIR}/lib)

configure_file(${CMAKE_CURRENT_SOURCE_DIR}/fix_pahomqttcpp.cmake.in 
               ${CMAKE_CURRENT_BINARY_DIR}/fix_pahomqttcpp.cmake @ONLY)


add_library(paho-mqttc3::MQTTClient STATIC IMPORTED GLOBAL)
set_target_properties(paho-mqttc3::MQTTClient PROPERTIES
	 IMPORTED_LOCATION ${PAHOMQTTC_TARGET_DIR}/lib/libpaho-mqtt3c-static.a
	 INTERFACE_INCLUDE_DIRECTORIES ${PAHOMQTTC_TARGET_DIR}/include)
add_library(paho-mqttc3::MQTTAsync STATIC IMPORTED GLOBAL)
set_target_properties(paho-mqttc3::MQTTAsync PROPERTIES
	 IMPORTED_LOCATION ${PAHOMQTTC_TARGET_DIR}/lib/libpaho-mqtt3a-static.a
	 INTERFACE_INCLUDE_DIRECTORIES ${PAHOMQTTC_TARGET_DIR}/include)
```

## pahomqttcpp.cmake
```
#
# Builds the paho.mqtt.cpp library
#
# Outputs the following target:
#   paho-mqttpp3
#
include(ExternalProject)
set(PAHOMQTTCPP_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lib/paho.mqtt.cpp)
set(PAHOMQTTCPP_TARGET_DIR ${CMAKE_CURRENT_BINARY_DIR}/paho.mqtt.cpp)
set(PAHOMQTTCPP_STATIC_LIB ${PAHOMQTTCPP_TARGET_DIR}/lib/libpaho-mqttpp3.a) 

file(MAKE_DIRECTORY ${PAHOMQTTCPP_TARGET_DIR}/include)

set(PAHO_BUILD_SHARED FALSE)
if(NOT ${PAHO_BUILD_STATIC})
  set(PAHO_BUILD_SHARED TRUE)
endif()

ExternalProject_Add(
    pahomqttcpp
	 DEPENDS pahomqttc
    PREFIX ${PAHOMQTTCPP_TARGET_DIR}
    SOURCE_DIR ${PAHOMQTTCPP_DIR}
	 CMAKE_ARGS -DCMAKE_PROJECT_paho-mqtt-cpp_INCLUDE=${CMAKE_CURRENT_BINARY_DIR}/fix_pahomqttcpp.cmake
	 CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${PAHOMQTTCPP_TARGET_DIR}
	 CMAKE_ARGS -DPAHO_WITH_SSL=${PAHO_BUILD_WITH_SSL} 
	 CMAKE_ARGS -DPAHO_BUILD_STATIC=${PAHO_BUILD_STATIC} 
	 CMAKE_ARGS -DPAHO_BUILD_SHARED=${PAHO_BUILD_SHARED}
    BUILD_COMMAND make
    INSTALL_COMMAND make install
	 BUILD_BYPRODUCTS ${PAHOMQTTCPP_STATIC_LIB}
)

add_library(paho-mqttpp3 STATIC IMPORTED GLOBAL)

add_dependencies(paho-mqttpp3 pahomqttcpp)

set_target_properties(paho-mqttpp3 PROPERTIES IMPORTED_LOCATION ${PAHOMQTTCPP_STATIC_LIB})
set_target_properties(paho-mqttpp3 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${PAHOMQTTCPP_TARGET_DIR}/include)
```

**Comment by gocarlos** [comment] 2020-03-05 09:12
> On a side note, however, I've really been considering having the C++ library automatically build (and maybe link in) the optimal version of the C lib by including it as a Git submodule to this project. It's a common source of errors and frustration to have to build two separate libraries and get them working together if you only care about using the C++ lib.
> 
> I did something similar with the Paho Rust library, and it's eliminated a lot of confusion and problems. So I should probably do it here as well.

I think the way to go in the future is with a package manager ala conan https://conan.io/center/paho-mqtt-cpp/1.0.1 which auto resolves dependences etc. 

Using submodules is always a pain for software clearing

**Comment by keysight-daryl** [comment] 2020-04-30 19:01
I'd love to see someone from conan-center work together here on this to properly package up both the c and cpp libraries on conan-center with up to date recipe files and cmake files etc. and maybe all packaging of these libraries is just handled consistently like that, just pulling from conan-center-index and it 'just works'.

**Comment by fpagliughi** [comment] 2020-04-30 19:30
Yeah. That would be cool.

**Comment by keysight-daryl** [comment] 2020-04-30 20:02
what is really problematic is when the conan-center recipes have to patch the oem cmake files and possible conan settings (paho.mqtt.c used to have its own recipe that needed patched), etc.  At least at my company conan is the way forward and conan-center is leading the pack.  I think the issue is in understanding the handoff between the library source itself and the packaging and build configurations to make it 'just works'.

**Comment by gocarlos** [comment] 2020-04-30 21:04
I brought the C and cpp libs to conan center, everything should work out of the box

**Comment by gocarlos** [comment] 2020-04-30 21:05
Yes, the cmake patches have to be brought upstream

**Comment by keysight-daryl** [comment] 2020-05-01 14:51
Is conan-center updated with paho.mqtt.c 1.3.2 + paho.mqqt.cpp 1.1.1 or is it some patched customized branch

**Comment by Kemp-J** [comment] 2020-05-07 15:22
Just to confirm (as someone who uses neither git nor conan) - once these changes are in will we still be able to download the source releases of the C and C++ libraries and compile the same way we currently do as two separate steps?

**Comment by fpagliughi** [comment] 2020-05-07 15:38
@Kemp-J Yeah, probably. I'm really leaning on having the C++ library link in the C one so that people would only need to deal with it as one lib. Building, linking, and getting the two different libraries working together is a huge percentage of the support required for this project!

But that doesn't mean that you need to use Conan or Git. You would just need to tell the C++ build where to find the C sources on your local machine (or put it into a subdirectory).

If you *really* wanted to maintain them separately, that might still be an option, but I really don't think it will be the default in the long run.

**Comment by Kemp-J** [comment] 2020-05-07 15:46
That sounds fine to me. I'm happy to tell the C++ library where the C sources are and let it build both. At the moment I statically link the C++ library and dynamically link the C one (don't ask), but I'm not wedded to that. My main concern is to not add more software into my build process. Thanks :)

**Comment by keysight-daryl** [comment] 2020-05-07 15:59
I think it would be really sweet if the cpp wrappers were just folded directly into the c library and maintained together within the same repo and built/linked together with one recipe/cmake file with a single option to select the end library as either a simple C or a C++ wrapped library.

**Comment by zhouglu** [comment] 2020-05-22 01:07
> Found the alternative (or maybe it is the right way). I do `cmake` with
> 
> `cmake -DCMAKE_PREFIX_PATH=<absolute path to mqtt c install dir> -DPAHO_MQTT_C_LIBRARIES=<absolute path to c libraries> -DPAHO_MQTT_C_INCLUDE_DIRS=<absolute path to include headers> ..`
> and configuration passes, but build then fails:
> `/usr/bin/ld: cannot find ../../paho.mqtt.c/build/install/lib: File format not recognized`
> but my library is not in `../../paho.mqtt.c/build/install/lib`, but in `../paho.mqtt.c/build/install/lib`. I provide absolute path so somewhere in cmake it gets resolved to wrong relative path.
> 
> I also exported `LD_LIBRARY_PATH` to mqtt c built libraries but did not help.

command changed to the following line, everything will be OK.
cmake -DCMAKE_PREFIX_PATH=<absolute path to mqtt c install dir> -DPAHO_MQTT_C_LIBRARIES=<absolute path to c libraries>/libpaho-mqtt3a.so -DPAHO_MQTT_C_INCLUDE_DIRS=<absolute path to include headers>

**Comment by geoffrey-vl** [comment] 2021-12-04 15:29
@magiino, thx for https://github.com/eclipse/paho.mqtt.cpp/issues/225#issuecomment-586644232, it helped me tremendously.

I had to perform 2 small changes.

1. In `pahomqttc.cmake` I needed to add `file(MAKE_DIRECTORY ${PAHOMQTTC_TARGET_DIR}/include)`
2. In `pahomqttc.cmake`, change `libpaho-mqtt3a-static.a` into `libpaho-mqtt3a.a` and `libpaho-mqtt3c-static.a` into `libpaho-mqtt3c.a`

That aside, and a bit off-topic: for those working in VSCode, in the `.vscode\settings.json` file change the `cmake.generator` to `Unix Makefiles`.

**Comment by irishcarbomb777** [comment] 2022-02-17 14:39
> > Found the alternative (or maybe it is the right way). I do `cmake` with
> > `cmake -DCMAKE_PREFIX_PATH=<absolute path to mqtt c install dir> -DPAHO_MQTT_C_LIBRARIES=<absolute path to c libraries> -DPAHO_MQTT_C_INCLUDE_DIRS=<absolute path to include headers> ..`
> > and configuration passes, but build then fails:
> > `/usr/bin/ld: cannot find ../../paho.mqtt.c/build/install/lib: File format not recognized`
> > but my library is not in `../../paho.mqtt.c/build/install/lib`, but in `../paho.mqtt.c/build/install/lib`. I provide absolute path so somewhere in cmake it gets resolved to wrong relative path.
> > I also exported `LD_LIBRARY_PATH` to mqtt c built libraries but did not help.
> 
> command changed to the following line, everything will be OK. cmake -DCMAKE_PREFIX_PATH= -DPAHO_MQTT_C_LIBRARIES=/libpaho-mqtt3a.so -DPAHO_MQTT_C_INCLUDE_DIRS=

This solved my problem building on WSL!

**Comment by fpagliughi** [comment] 2024-06-17 12:42
A number of changes have been added to the CMake build in the last year, particularly to solve transitive dependencies with the Paho C library. A few more are going out with the v1.4.0 release this week. And more improvements are coming in the near future with some updates to the build for the Paho C library set to be released soon.

But the biggest hel may be from the new `PAHO_WITH_MQTT_C` build option that will automatically configure, compile, and install the Paho C library as part of the C++ build. In addition the eliminating a number of steps, it ensures the two libraries are configured in a compatible manner, ie static/shared, ssl, etc.

This should go a long way to make the C++ library "feel" stand-alone, and reduce the complexity of building them, particularly if you are just using the C++ API.

**Comment by fpagliughi** [comment] 2024-06-17 12:43
I will close this now, but please feel free to re-open or create a new issue if there are still problems with v1.4.

**Closed by fpagliughi** 2024-06-17 12:43 UTC
