### ISSUE TITLE
Build error in Xcode project

### ISSUE THREAD

**Issue by JSatyam** [eclipse/paho.mqtt.cpp#488] opened 2024-03-07 11:49 UTC
We try to build Paho v2.0 in C++ project in Xcode, Please check and help

Undefined symbols:
  _MQTTProperties_free, referenced from:
      mqtt::properties::~properties() in libcore-main.a[19](MqttClientHelper.o)
  mqtt::properties::properties(), referenced from:
      test::MqttClientHelper::connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libcore-main.a[19](MqttClientHelper.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fpagliughi** [comment] 2024-06-17 12:25
I haven't been able to reproduce this error. I'm not sure what version you're testing since there is not a v2.0 release of this library.

But a number of CMake build issues concerning transitive dependencies between the libraries have been resolved with the latest code that is about to be released in v1.4 (currently in master), so please try that out, and let us know if it fixes the problem.

**Comment by fpagliughi** [comment] 2024-07-04 20:08
Actually I just saw this error on another project when I accidentally chose the C compiler tools (clang) instead of the C++ ones (clang++).

**Closed** 2024-07-07 03:33 UTC
