### ISSUE TITLE
async_subscribe.cpp example receives twice the on_success() notification for connection

### ISSUE THREAD

**Issue by whizmo** [eclipse/paho.mqtt.cpp#129] opened 2017-10-20 10:35 UTC
I configured the example to connect to the test server "tcp://test.mosquitto.org:1883"
This is the output:

> $ ./src/samples/async_subscribe 
> Connecting to the MQTT server...
> Connection success
> 
> Subscribing to topic 'hello'
> 	for client async_subcribe_cpp using QoS1
> 
> Press Q<Enter> to quit
> 
> 
> Connection success
> 
> Subscribing to topic 'hello'
> 	for client async_subcribe_cpp using QoS1
> 
> Press Q<Enter> to quit
> 
> Subscription success for token: [1]
> 	token topic: 'hello', ...
> 
> Message arrived
> 	topic: 'hello'
> 	payload: 'hi'
> 
> Subscription success for token: [2]
> 	token topic: 'hello', ...
> 
> Message arrived
> 	topic: 'hello'
> 	payload: 'hi'
> 
> Message arrived
> 	topic: 'hello'
> 	payload: 'snsfgsnb'
> 
> Q

**Comment by fpagliughi** [comment] 2017-10-20 13:26
That's an odd one. I'll see if I can recreate it.

**Comment by cavalleydude** [comment] 2017-11-30 21:44
I'm seeing this too. Somehow, it appears as 2 connections or 2 instances of the callback are being used. For me, the connection drops and reconnects over and over again. I've seen other reports that this is caused by 2 clients using the same clientID, but in my case... it's just one call from one unique client... the callbacks act like there are 2 users of the callback.

**Comment by dereknex** [comment] 2018-03-06 08:56
I get the same issue. Anyone figure out a solution?

**Comment by whizmo** [comment] 2018-03-06 12:39
I use the method mqtt::callback::connected() which is only called once.

**Comment by fpagliughi** [comment] 2018-03-22 14:44
Apologies for the slow response, but I'm finally getting back to working on the C++ library now...

It seems that the C++ callback is being fired in response to both the "connect success" *and* the *connected* events from the C library. With the Paho C logging enabled, we see:

```
20180322 102922.576 Calling connect success for client async_subcribe_cpp
[callback]
Connection success

Subscribing to topic 'hello'
	for client async_subcribe_cpp using QoS1

Press Q<Enter> to quit

20180322 102922.576 (468702976)  (1)< Thread_wait_cond:382 (0)
...
20180322 102922.577 (460310272)  (1)< MQTTAsync_subscribe:2598 (0)
20180322 102922.577 Calling connected for client async_subcribe_cpp
<calback>
Connection success
```

I will fix it.

**Comment by fpagliughi** [comment] 2018-03-22 19:26
I updated the _async_subscribe_ sample to use the _connected()_ callback, since that seems more natural/obvious as to what's happening. But the _on_succes()_ callback is fixed. It should only fire once now.

**Comment by bzhmaddog** [comment] 2018-09-28 08:53
Hi. Somehow I am still having this issue

**Comment by FullColon** [comment] 2018-11-15 20:10
I am experiencing this still too

**Comment by fpagliughi** [comment] 2018-11-15 21:09
What platform is giving you all trouble?

**Comment by FullColon** [comment] 2018-11-15 21:40
Windows 64 Visual Studio 14 2015 for me

**Comment by bzhmaddog** [comment] 2018-11-15 21:53
ArmV8 (raspbian)

**Comment by lgilson** [comment] 2018-12-03 17:52
Windows 64 Visual Studio 2017 here.

The strange thing is i don't see the call to connected(), just 2x on_succes().

**Comment by fpagliughi** [comment] 2018-12-11 03:45
The fix is in the Git repository in the 'master' branch. It has not yet be included in a formal release. (There has not been a release since this bug was initially reported).

The call to connect() is clearly added in the commit for this bug:
https://github.com/eclipse/paho.mqtt.cpp/commit/d15b2e74c40164eca66e41fea27acb529f428692

I don't know if the problem has been that the commit was merged into the 'develop' branch, and not master. But it's there now, and I've tried this on Ubuntu, Win7 (VS2015), and a RaspberryPi. 
They all look good to me.

**Closed** 2019-10-10 20:42 UTC
Labels: bug

**Comment by fpagliughi** [comment] 2019-10-10 20:44
I closed this as I hadn't heard of any complaints in a while, and I was still unable to reproduce. Anyone... feel free to re-open if this comes up again.

**Comment by MHeshamG** [comment] 2021-10-18 11:30
Hello,

I still get the issue, I am using raspberry pi 4 and i have used the build script for paho mqtt c after checking out branch 1.3.9.
Here is my code
```
#include <iostream>
#include "MqttClient.hpp"

using CommunicationChannels::MqttClient;

class MqttBusinessClient 
{
public:
    MqttBusinessClient() : mqttClient{DFLT_SERVER_ADDRESS, CLIENT_ID} {}
    void connect()
    {
        mqttClient.connect([this](bool status){
            if(status){
                i++;
                std::cout << "\nConnection success " <<i<< std::endl;
                //onConnect();
                subscribe();
            }
            else{
                std::cout << "\nConnection Failed" << std::endl;
            }
        });
    }

    void subscribe(){
        std::cout << "\nSubscribing to topic '" << TOPIC << "'\n"
                << "\tfor client " << CLIENT_ID
                << " using QoS" << QOS << "\n"
                << "\nPress Q<Enter> to quit\n" << std::endl;
        mqttClient.subscribe(TOPIC, QOS, [](bool status){
            std::cout<<"Subscribtion status: "<<status<<std::endl;
        });
    }

    void publish(){
        mqttClient.publish("test/topic", "Hello 2");
        std::cout << "  ...OK Sent" << std::endl;
    }

private:
    const std::string DFLT_SERVER_ADDRESS	{ "tcp://localhost:1883" };
    const std::string CLIENT_ID				{ "mqtt_client" };
    const std::string TOPIC                 {"test/topic"};
    const int	QOS = 0;

    int i =0;

    MqttClient mqttClient;

    void onConnect(){
        subscribe();
        publish();
    }
};

int main(int argc, char* argv[])
{
    MqttBusinessClient cli;
    cli.connect();
    while (std::tolower(std::cin.get()) != 'q');
}
```

```
#include "mqtt/async_client.h"
#include <iostream>
#include <string>
#include <vector>


namespace CommunicationChannels{

    // Callbacks for the success or failures of requested actions.
    // This could be used to initiate further action, but here we just log the
    // results to the console.

    class action_listener : public virtual mqtt::iaction_listener
    {
        std::function<void (bool)> m_onAction;

        void on_failure(const mqtt::token& tok) override {
            if(m_onAction != nullptr)
                m_onAction(false);
        }

        void on_success(const mqtt::token& tok) override {
            if(m_onAction != nullptr)
                m_onAction(true);
        }

    public:
        void setOnAction(std::function<void (bool)> onAction)
        {
            m_onAction = onAction;
        }
        action_listener() = default;
        action_listener (const action_listener&) = delete;
        action_listener& operator= (const action_listener&) = delete;
    };

    /**
     * Local callback & listener class for use with the client connection.
     * This is primarily intended to receive messages, but it will also monitor
     * the connection to the broker. If the connection is lost, it will attempt
     * to restore the connection and re-subscribe to the topic.
     */
    class callback : public virtual mqtt::callback
    {
        // Callback for when the connection is lost.
        // This will initiate the attempt to manually reconnect.
        void connection_lost(const std::string& cause) override {
            std::cout << "\nConnection lost" << std::endl;
            if (!cause.empty())
                std::cout << "\tcause: " << cause << std::endl;
        }

        // Callback for when a message arrives.
        void message_arrived(mqtt::const_message_ptr msg) override {
            std::cout << "Message arrived" << std::endl;
            std::cout << "\ttopic: '" << msg->get_topic() << "'" << std::endl;
            std::cout << "\tpayload: '" << msg->to_string() << "'\n" << std::endl;
        }
    };

    class MqttClient
    {
        public:
            MqttClient(std::string brokerAddress, std::string clientId);
            void connect(std::function<void (bool)> onConnect = nullptr);
            void publish(std::string topic, std::string msg);
            void subscribe(std::string topic, int qos, std::function<void (bool)> onSubscribtion = nullptr);
            void subscribe(std::vector<std::string> topics, std::vector<int> qos, std::function<void (bool)> onSubscribtion = nullptr);
        private:
            mqtt::async_client m_mqttClient;
            callback cb;
            action_listener m_conectionListener;
            action_listener m_subListener;
            action_listener m_subListListener;
            
    };
}
```

```
#include "MqttClient.hpp"

using namespace CommunicationChannels;

MqttClient::MqttClient(std::string brokerAddress, std::string clientId) : m_mqttClient{brokerAddress, clientId}
{
	std::cout << "Initializing for server '" << brokerAddress << "'..." << std::endl;
	m_mqttClient.set_callback(cb);
}

void MqttClient::connect(std::function<void (bool)> onConnect)
{
	m_conectionListener.setOnAction(onConnect);

	auto connOpts = mqtt::connect_options_builder()
						.clean_session()
						.finalize();

	try
	{
		std::cout << "\nConnecting..." << std::endl;
		m_mqttClient.connect(connOpts,nullptr,m_conectionListener);
	}
	catch (const mqtt::exception &exc)
	{
		std::cerr << exc.what() << std::endl;
	}
}

void MqttClient::subscribe(std::string topic, int qos, std::function<void (bool)> onSubscribtion)
{
	m_subListener.setOnAction(onSubscribtion);
	m_mqttClient.subscribe(topic, qos, nullptr, m_subListener);
}

void MqttClient::subscribe(std::vector<std::string> topics, std::vector<int> qos, std::function<void (bool)> onSubscribtion)
{
	m_subListListener.setOnAction(onSubscribtion);
	auto convertedTopics = mqtt::string_collection::create(topics);
	m_mqttClient.subscribe(convertedTopics, qos, nullptr, m_subListListener);
}

void MqttClient::publish(std::string topic, std::string msg)
{
	try
	{
		std::cout << "\nSending message..." << std::endl;
		mqtt::message_ptr pubmsg = mqtt::make_message(topic, msg);
		m_mqttClient.publish(pubmsg);
		
	}
	catch (const mqtt::exception &exc)
	{
		std::cerr << exc.what() << std::endl;
	}
}
```

**Comment by landersson** [comment] 2021-11-19 13:19
I think I also just ran into this. on_success() on a token returned from async_client::connect() is called twice:

Attached below are backtraces leading up to each of the two calls to on_success:

![image](https://user-images.githubusercontent.com/2536670/142628589-db58a7e0-2471-43b3-96aa-b36c22be006c.png)

I'm using paho.mqtt.cpp rev 2ff3d155dcd10564f1816675789284b4efd79eb7 with paho.mqtt.c 1.3.9.

**Comment by mtrx** [comment] 2022-01-25 09:25
I can also confirm that completion handler on_success() is called twice. My implementation uses paho.mqtt.cpp 1.2.0 and paho.mqtt.c 1.3.9.

The fix mentioned in https://github.com/eclipse/paho.mqtt.cpp/issues/129#issuecomment-446062296 is not (or no longer) included in async_client.cpp. There is still the call to `token::on_success()` in `async_client::on_connected()`.
