### ISSUE TITLE
terminate called after throwing an instance of 'mqtt::exception'  what(): MQTT error [-11]: Aborted

### ISSUE THREAD

**Issue by guoziqiangYY** [eclipse/paho.mqtt.cpp#176] opened 2019-01-29 09:29 UTC
Some problems have been encountered in the course of use.
I'm using asyncClient for asynchronous pubishi. When I use async_client-> publish (message_ptr). wait_for (1000L), if the network is disconnected at this time. Then the error will occur like this
```
terminate called after throwing an instance of 'mqtt::exception'  what(): MQTT error [-11]: 
Aborted
```
and my application is crash. How to solve this problem?

**Comment by KaleXia** [comment] 2019-01-29 09:35
And  Can I use async_client  for synchronous push? OR both of client and async_client all existence  at the same time.

**Comment by Radagan** [comment] 2019-07-02 06:47
@fpagliughi I'm getting the same MQTT error [-11] when I call client.is_connected() and the network is down. I'm trying to maintain a persistant connection to Google IoT Core and I was testing reconnect. Why would it not simply return false?

**Comment by frank-metal** [comment] 2019-07-02 16:02
You're right. It should just return _false_. I'll see if I can reproduce this behavior and then fix it.

I haven't worked with Google IoT, but the reconnect() is just a convenience function. You should always be able to call connect again with the original login information to restore the connection.

**Comment by fpagliughi** [comment] 2019-07-02 16:05
You're right. It should just return false. I'll see if I can reproduce this behavior and then fix it.

I haven't worked with Google IoT, but the reconnect() is just a convenience function. You should always be able to call connect again with the original login information to restore the connection.

**Comment by Radagan** [comment] 2019-07-03 00:07
Thanks. If you need help reproducing it, let me know. In the Google IoT case I have, I need to change out the password in the original login, so I call connect with a new mqtt::connect_options.

**Comment by divyasharma19** [comment] 2020-01-28 09:16
@fpagliughi  I am getting an error while creating a consumer.
**terminate called after throwing an instance of 'mqtt::exception'
  what():  MQTT error [-3]: Disconnected
I am not getting any solution for this.**
My publisher is working fine. Consumer is getting disconnected while publishing.
Looking forward to you.
Thanks.

**Comment by fpagliughi** [comment] 2020-01-28 12:36
@divyasharma19 The library is saying that it is unable to perform an operation because it's disconnected from the server. Are you sure that you created a proper connection and that nothing is causing it to break in the operation of the consumer? 

Unfortunately, with MQTT v3, the server can disconnect you for an invalid operation and not tell you why it disconnected. That is being fixed with MQTT v5 and "ReasonCodes".

But this sounds like a different problem than this reported issue of Error: -11. So perhaps you should create a new issue and post some minimal code that you have and/or some additional information about what you're doing, and then perhaps we can help.

**Comment by fpagliughi** [comment] 2020-12-23 02:58
Closing from inactivity. Feel free to reopen this if it is still an issue.

**Closed by fpagliughi** 2020-12-23 02:58 UTC

**Comment by Vaarall** [comment] 2023-09-25 02:41
catch the exception, then reconnect.
