### ISSUE TITLE
Build of v1.1 on Debian fails with missing symbol ::Log

### ISSUE THREAD

**Issue by beewoolie** [eclipse/paho.mqtt.cpp#302] opened 2020-11-04 19:49 UTC
```
Scanning dependencies of target async_publish_time
[ 40%] Building CXX object src/samples/CMakeFiles/async_publish_time.dir/async_publish_time.cpp.o
[ 42%] Linking CXX executable async_publish_time
/usr/bin/ld: ../libpaho-mqttpp3.so.1.1.0: undefined reference to `Log'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/samples/CMakeFiles/async_publish_time.dir/build.make:107: src/samples/async_publish_time] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:331: src/samples/CMakeFiles/async_publish_time.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2

```
In the source for async_publish_time.cpp, there is a call to ::Log that looks like it is bypassing headers with an explicit import.   The symbol is in the library installed on the system.  Perhaps this is an issue with the link order?

**Comment by fpagliughi** [comment] 2020-11-04 22:06
Duplicate of #211 and #223 
The fix is in master, set for the next release.

**Comment by fpagliughi** [comment] 2020-11-19 14:48
Closing this. Look to the referenced issues for details.

**Closed by fpagliughi** 2020-11-19 14:48 UTC
