### ISSUE TITLE
SSL support is not working

### ISSUE THREAD

**Issue by phariprasadreddy** [eclipse/paho.mqtt.cpp#19] opened 2016-08-30 12:24 UTC
I have tried to SSL options to connect and it is not working.
Basically I have .pem file and providing it in the truststore and trying to connect.
Here is the code I have used to set SSL properties.

```
mqtt::ssl_options ssl;
ssl.set_trust_store(TRUST_STORE);
ssl.set_enable_server_cert_auth(0);
connectOptions.set_ssl(ssl);
```
 Then it has coredumped.
Here is the output I am seeing in the console:

 ```
Setting SSL properties
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```

I have commented out part of code in set_ssl in the connect_options.cpp as below

```
void connect_options::set_ssl(const ssl_options& ssl)
{
	ssl_.set_trust_store(ssl.get_trust_store());
	/*ssl_.set_key_store(ssl.get_key_store());
	ssl_.set_private_key(ssl.get_private_key());
	ssl_.set_private_key_password(ssl.get_private_key_password());
	ssl_.set_enabled_cipher_suites(ssl.get_enabled_cipher_suites());*/
	ssl_.set_enable_server_cert_auth(ssl.get_enable_server_cert_auth());

	opts_.ssl = &ssl_.opts_;
}
```

Then I am seeing MQTT exception as below:

` Error: MQTT exception -1 `

Please let me know if you have any working sample.

Thanks,
Hari.

**Comment by guilhermeferreira** [comment] 2016-08-30 20:09
Hello @phariprasadreddy,

Please update your code with the develop branch. @fpagliughi has improved the code for the `ssl_options` class.

This problem happens because the `ssl_options` class is calling the `std::string` constructor with an invalid (`nullptr`) `const char*`. You must feed all the SSL strings, not only the trust_store. The default `ssl_options` constructor uses `MQTTAsync_SSLOptions_initializer`, which initializes all strings to NULL. The code bellow generates the same problem:

`const char* c = nullptr;`
`std::string s(c);`

**Comment by fpagliughi** [comment] 2016-08-30 23:42
Fixed in commit 2dd74796d5ef4e26fa1f0a74f1e4ec8b9cf08e2f currently in the develop branch.

**Closed by fpagliughi** 2016-08-30 23:42 UTC

**Comment by phariprasadreddy** [comment] 2016-08-31 08:44
@guilhermeferreira @fpagliughi Thanks for quick response. The first issue that is reported is fixed. 
However, after setting ssl options and I am trying to connect then I am getting MQTT Exception as below.
```
Error: MQTT exception -1
```
Please let me know if you have any sample connecting with ssl.

Thanks,
Hari.

**Comment by guilhermeferreira** [comment] 2016-09-06 01:31
@phariprasadreddy I'll need more time to check what is happening. But meanwhile, were you able to set this connection  up using Paho C? Just to know if the problem is within the Paho C++, Paho C or your certificates and authentication files.

**Comment by phariprasadreddy** [comment] 2016-09-07 05:36
@guilhermeferreira Yes I have checked with Paho C it is working fine. Same pem file I am using for connecting with Paho C++.

Thanks,
Hari.

**Comment by guilhermeferreira** [comment] 2016-09-10 09:32
Hello @phariprasadreddy,

There is a bug in this implementation. I'm going to upload a patch next week.

The ssl_options class initializes the MQTTAsync_SSLOptions char pointers even if the members are empty [https://github.com/eclipse/paho.mqtt.cpp/blob/develop/src/ssl_options.cpp#L37]. But it turns out the Paho MQTT C considers a invalid value only if the pointer is null [https://github.com/eclipse/paho.mqtt.c/blob/master/src/SSLSocket.c#L478]. And it ends up using the empty SSL parameters empty-initialized by Paho C+×.

So, for the C++ library an invalid SSL parameter can be bith null or empty, while  fir thr C library only null represents invalid value.

**Comment by guilhermeferreira** [comment] 2016-09-11 06:26
The pull request #20 solves this issue. Using this fix you will be able to connect with a server using a valid certificate.
